version: '3'
services:
  message:
    image: edwinlll/uchat4influxdb:latest
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - DEBUG=true
    volumes:
      - ./.uchat4influxdb.yaml:/root/.uchat4influxdb.yaml
    command: >
      sh -c "ln -snf /usr/share/zoneinfo/$${TZ} /etc/localtime && 
      echo $${TZ} > /etc/timezone &&
      cd /root && uchat4influxdb message"
