version: '3'
services:
  message:
    image: edwinlll/uchat4influxdb:latest
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - DEBUG=true
    volumes:
      - ./.uchat4influxdb.yaml:/usr/local/uchat4influxdb/.uchat4influxdb.yaml
    command: ["message"]
  member_join:
    image: edwinlll/uchat4influxdb:latest
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - DEBUG=true
    volumes:
      - ./.uchat4influxdb.yaml:/usr/local/uchat4influxdb/.uchat4influxdb.yaml
    command: ["memeber_join"]
  member_quit:
    image: edwinlll/uchat4influxdb:latest
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - DEBUG=true
    volumes:
      - ./.uchat4influxdb.yaml:/usr/local/uchat4influxdb/.uchat4influxdb.yaml
    command: ["memeber_quit"]
